In [107]:
import numpy as np

In [108]:
# Broadcasting 2D + 1D array

x = np.ones([3,3])
print(x,"\n")
y = np.arange(3)
print(y,"\n")
print(x+y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[0 1 2] 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [109]:
# Broadcast both arrays

a = np.arange(3)
print(a,"\n")
a = a[:,np.newaxis] # newaxis = 새로운 차원을 추가
print(a,"\n")
b = np.arange(3)
print(b,"\n")
print(a+b)

[0 1 2] 

[[0]
 [1]
 [2]] 

[0 1 2] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [110]:
"""
Broadcasting Rules
"""

a = np.ones((2,3))
print(a)

b = np.arange(3)
print(b)

print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [111]:
"""
Comparisons, Masks, and Boolean Logic
"""

x = np.array([1,2,3,4,5])
print(x)

print(x < 3)
print(x >= 3)
print(x != 3)
print(x == 3)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [112]:
# bool maskong for multi-dimensional arrays

np.random.seed(0)
x = np.random.randint(10, size=(3, 4)) # 0~9까지의 정수 , 3by4 배열
print(x, "\n")

print(x < 6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [113]:
"""
Working with Boolean Arrays
"""

print(x,"\n")
print(np.count_nonzero(x < 6)) # x < 6 의 총 갯수
print(np.sum(x < 6))
print(np.any(x > 9))
print(np.all( x > 1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

8
8
False
False


In [114]:
# Masking operations

print(x,"\n")
print( x < 5,"\n")
print(x[x < 5],"\n")
print(np.mean(x[x < 5]))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]] 

[0 3 3 3 2 4] 

2.5


In [115]:
"""
Fancy Indexing
"""

np.random.seed(1)
x = np.random.randint(100, size=10)
print(x)

print(x[2], x[4], x[6])

ind = [2, 4, 6]
print(x[ind])

[37 12 72  9 75  5 79 64 16  1]
72 75 79
[72 75 79]


In [116]:
# For n-D arrays

np.random.seed(2)
x = np.random.randint(10, size=(3, 5))
print(x)

row = [0, 1, 2]
col = [1, 3, 2]

print(x[row, col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[8 5 7]


In [117]:
# For n-D arrays with broadcasting

print(x)
row = np.array([0,1,2])
col = np.array([2,1,4])

print(x[row[:, np.newaxis],col])

#broadcasting

# row =  0 0 0
#        1 1 1
#        2 2 2

# col =  2 1 4
#        2 1 4
#        2 1 4

# [row,col] = 0,2 0,1 0,4
#              1,2 1,1 1,4
#              2,2 2,1 2,4

# x[row,col] = 6 8 8
#              1 2 4
#              7 5 6

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[[6 8 8]
 [1 2 4]
 [7 5 6]]


In [118]:
"""
Combined Indexing
"""

x = np.arange(1,13).reshape(3,4)
print(x,"\n")

print(x[2,[2, 0, 1]],"\n")
print(x[1:, [2, 0, 1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[11  9 10] 

[[ 7  5  6]
 [11  9 10]]
